name: Build and deploy

on:
  push:
    branches: [master]

  workflow_dispatch:

env:
  FRONTEND_IMAGE: ghcr.io/${{ github.repository }}/rubix:sha-${{ github.sha }}
  LATEST_FRONTEND_IMAGE: ghcr.io/${{ github.repository }}/rubix:latest

jobs:
  frontend-build:
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Repo
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub container registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push tag container
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile
          tags: ${{ env.FRONTEND_IMAGE }}
          push: true

  deploy:
    needs:
      - frontend-build

    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub container registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push latest container images
        run: |
          echo "Push client container to latest tag"
          docker pull $FRONTEND_IMAGE
          docker tag $FRONTEND_IMAGE $LATEST_FRONTEND_IMAGE
          docker push $LATEST_FRONTEND_IMAGE

      - name: Trigger the deployment pipeline
        run: |
          curl --request POST \
          --form "token=${{ secrets.DEPLOY_TRIGGER_TOKEN }}" \
          -F "variables[ANSIBLE_PLAYBOOK]=rubix.deploy.yml" \
          --form ref=master "${{ secrets.DEPLOY_TRIGGER_URL }}"
